Release 5.2.0
microsoft/onefuzz pull request #1701
Opened 2022-03-09 21:40 UTC by mgreisen

## Summary of the Pull Request

_What is this about?_

## PR Checklist
* [ ] Applies to work item: #xxx
* [ ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/onefuzz) and sign the CLI.
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Info on Pull Request

_What does this include?_

## Validation Steps Performed

_How does someone test & validate?_

2022-03-09 21:41 UTC, tevoinea approved these changes

2022-03-09 21:43 UTC, stishkin approved these changes

2022-03-10 00:17 UTC, ranweiler requested changes

2022-03-10 00:17 UTC, ranweiler commented on CHANGELOG.md
> +* Service: Added additional auto scaling support for VM scale sets. [#1686](https://github.com/microsoft/onefuzz/pull/1686), [#1698](https://github.com/microsoft/onefuzz/pull1698)
```suggestion
* Service: Added additional auto-scaling support for VM scale sets. [#1686](https://github.com/microsoft/onefuzz/pull/1686), [#1698](https://github.com/microsoft/onefuzz/pull/1698)
```

2022-03-10 00:40 UTC, ranweiler approved these changes

2022-03-10 17:35 UTC, chkeita approved these changes

2022-03-10 19:30 UTC, merged