#344: Multi-tenant authentication support in CLI
microsoft/onefuzz pull request #346
Opened 2020-11-27 17:38 UTC by anslutsk

## Summary of the Pull Request

These are purposed changes to resolve ticket #344 

I have tested these changes and it does not effect or break the current functionality.

I don't necessarily expect this PR to be merged without some tweaks. I'll coordinate over the next week or so to get it right.

One coding issue I would like to discuss/highlight is the assumption (in code) that if "--tenant_domain" is used then the 'common' authority is also used. I am open to suggestions. 

## PR Checklist
* [X] Applies to work item: #344
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/onefuzz) and sign the CLI.
* [X] Tests passed (with and without multitenant authentication)
* [?] Requires documentation to be updated
* [No] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #344

## Info on Pull Request

Minor changes to the config file and the login process.

## Validation Steps Performed

Tested these changes with a multi-tenant enabled endpoint and a single-tenant endpoint.

2020-11-30 18:24 UTC, bmc-msft requested changes

2020-11-30 18:24 UTC, bmc-msft commented on src/cli/onefuzz/backend.py
> +        if "common" in self.config.authority:
Instead of checking for `common`, can you check if tenant_domain is not None?

2020-12-01 02:33 UTC, bmc-msft commented on src/cli/onefuzz/backend.py
> +        if "common" in self.config.authority:
```suggestion
        if self.config.tenant_domain:
```

2020-12-01 02:34 UTC, bmc-msft commented on src/cli/onefuzz/backend.py
```suggestion


```

2020-12-08 22:40 UTC, anslutsk reviewed
Looks good!

2020-12-11 23:40 UTC, anslutsk commented
Anything I should do to have this merged?

2020-12-16 12:57 UTC, bmc-msft commented
@anslutsk , there is an issue with Unicode.  I made https://github.com/anslutsk/onefuzz/pull/2 to address this issue.  If you merge that PR into your fork, this PR should be good to go.

2021-01-06 12:34 UTC, bmc-msft approved these changes

2021-01-06 12:35 UTC, merged